export default {
    USER_LOG_IN: "USER_LOG_IN",
    SET_ADVT: "SET_ADVT",
    CHANGE_PUBLISH_STATE: "CHANGE_PUBLISH_STATE",
    SHOW_NOTIFICATION:"SHOW_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION"
}